apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: timescaledb:5432
    database: iot_demo
    user: iot_user

    secureJsonData:
      password: iot_password

    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true

    isDefault: true
    editable: true